#!/usr/bin/env bash
sources=
config=
for path in "$@" ; do
  if [[ -e "$path" ]] ; then
    if [[ "$path" == *.yml || "$path" == *.yaml ]] ; then
      if [[ -n "$config" ]] ; then
        echo -e '\033[0;31m[FATAL] [unbag2] multiple yaml files provided, please only give one file.\033[0m'
        exit 1
      fi
      config="$path"
    else
      if [[ -z $sources ]] ; then
        sources="$path"
      else
      sources="$sources $path"
      fi
    fi
  fi
done
if [[ -n "$config" ]] ; then
  ros2 launch unbag2 unbag2.py "files:=\"$sources\""
else
  ros2 launch unbag2 unbag2.py "files:=\"$sources\" yaml:=\"$config\""
fi
exit 0